---
title: "Review_Ms. Figuras"
author: "Giorgia Graells"
output: pdf_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(patchwork)
library(ggplot2)
```


```{r}
DF <- read_csv("WebScience_Ref.csv")
```


```{r Years}
Pub_year <-ggplot(DF) + geom_bar(aes(x = `Publication Year`))+  labs(y="Number of articles", x="Publication year")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))
Pub_year
```


```{r Locations}
DF_Location <- DF %>%  group_by(`Study location`) %>% summarise(n = n()) %>% ungroup() %>% dplyr::filter(!is.na(`Study location`)) %>% 
  mutate(`Study location`=fct_reorder(`Study location`, -n))

DF_Location2 <- DF_Location %>% 
  mutate(`Study zone`= case_when(`Study location` %in% c("3 regions", "4 regions", "5 regions", "More than 5 regions")~"Various regions of Chile",  `Study location` %in% c("PNP", "AANP", "VPRNP")~"National Parks", `Study location` %in% c("Adjacent to PNP", "Adjacent to AANP", "Adjacent to VPRNP")~"Adjacent areas to NP", `Study location` %in% c("2 regions", "Andes of Los Rios Region", "Neuquen, Argentina", "Argentinian andes")~"Similar ecosystems", `Study location` %in% c("Los Lagos Region")~"Larger areas that comprise the NP", `Study location` %in% c("Chile", "Chile and Argentina")~"Global studies")) %>%
  mutate(`Study zone`= str_wrap(`Study zone`, 18))
                                
Location2 <-ggplot(DF_Location2, aes(x = fct_reorder(`Study zone`,n, .desc=TRUE), y = n, group = `Study location`)) + geom_col(aes(fill=`Study zone`), position="dodge", color="black") + geom_text(aes(label = `Study location`), size=4, position=position_dodge(0.9), angle=90,vjust=0.5, hjust=-0.04 ) + labs(y="Number of articles", x="Study locations")  + theme_classic()+ ylim(c(0,66))+theme(legend.position = "none")+ scale_fill_brewer(palette = "Dark2") + theme(text=element_text(size=18,  family="Times"), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
Location2
```


```{r Areas, fig.height=10, fig.width=8}
DF_Area <- DF %>%  group_by(`Area of study`, `Study location`) %>% summarise(n = n()) %>% ungroup() %>%
  mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% dplyr::filter(!is.na(`Area of study`))

p1 <-ggplot(DF_Area) + geom_col(aes(x = `Area of study`, y=n)) +labs(y="Number of articles", x="Area of study")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 

DF_Area2 <- DF_Area %>% dplyr::filter(`Study location` %in% c("PNP", "VPRNP", "AANP"))
p2 <- ggplot(DF_Area2) + geom_col(aes(x = `Area of study`, y=n)) +labs(y="Number of articles", x="Area of study")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + facet_wrap(~`Study location`, scales="free_x")

p1/p2
```


```{r}
DF_Methodology <- DF %>%  group_by(Methodology) %>% summarise(n = n()) %>% ungroup() %>% dplyr::filter(!is.na(Methodology)) %>% mutate(Methodology=fct_reorder(Methodology, -n))

DF_Methodology <- DF_Methodology %>% 
  mutate(General_methods= case_when(
    Methodology %in% c("Field collection", "dendrochronology", "Electric fishing")~"Field collection",  
    Methodology %in% c("Field survey", "Sampling stations")~"Field survey", 
    Methodology %in% c("Field experiment", "Transplant experiment", "Seedling experiment")~"Field experiment", 
    Methodology %in% c("Communicational strategy", "Discussion", "Quantitative and qualitative methods", "Survey", "Interview")~"Social methods", 
    Methodology %in% c("Modeling", "Simulations", "spatially explicit model", "Multivariate model")~"Modeling", 
    Methodology %in% c("Chile", "Chile and Argentina")~"Global studies",
    Methodology %in% c("Genetic analysis", "Reconstruction of mtDNA")~"Genetic analysis",
    Methodology %in% c("Review of literature")~"Review of literature")) %>%
  mutate(General_methods= str_wrap(General_methods, 18))


p1 <-ggplot(DF_Methodology, aes(x = fct_reorder(General_methods, n, .desc=TRUE), y = n, group = Methodology)) + geom_col(aes(fill=General_methods), position="dodge", color="black") + geom_text(aes(label =Methodology), size=4, position=position_dodge(0.9), angle=90,vjust=0.5, hjust=-0.04 ) + labs(y="Number of articles", x="Study locations")  + theme_classic()+ ylim(c(0,66))+theme(legend.position = "none")+ scale_fill_brewer(palette = "Dark2") + theme(text=element_text(size=18,  family="Times"), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
p1


```


```{r Process, fig.height=10}
DF_Process <- DF %>%  group_by(`Area of study`, Process, Methodology, `Study object`) %>% summarise(n = n()) %>% ungroup() %>% 
  dplyr::filter(!is.na(`Area of study`))
#%>% mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% 

plot_process <-ggplot(DF_Process) + geom_col(aes(x = Process, y=n)) +labs(y="Number of articles", x="Processes studied")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + facet_wrap(~`Area of study`, scales="free_x")
plot_process
```


```{r Object}
DF_object <- DF %>%  group_by(`Study object`) %>% summarise(n = n()) %>% ungroup() %>% dplyr::filter(!is.na(`Study object`)) %>% mutate(`Study object`=fct_reorder(`Study object`, -n))

DF_object <- DF_object %>% 
  mutate(General_object= case_when(
    `Study object` %in% c("People", "Urban areas")~"Social",  
    `Study object` %in% c("Aegorhinus", "Austrocedrus", "Bird species","Chusquea", "Didymosphenia", "Dromiciops", "F. cupressoides", "Lichen", "Nothofagus", "Fishes",  "Salmonids", "Liolaemus", "Wild boar")~"Species", 
    `Study object` %in% c("Lakes", "Groundwater Storage", "runoff", "Soil", "watershed")~"Geographic elements", 
    `Study object` %in% c("Native forest")~"Ecosystem",
    `Study object` %in% c("Precipitation", "Rock art", "Fires","Particulate matter" )~"a",
    `Study object` %in% c("Aquatic plants" )~"Group of plants",
    `Study object` %in% c("Crustacean", "Evergreen trees")~"b")) %>%
  mutate(General_object= str_wrap(General_object, 18))


#p1 <-ggplot(DF_object, aes(x = fct_reorder(General_object, n, .desc=TRUE), y = n, group = `Study object`)) + geom_col(aes(fill=General_object), position="dodge", color="black") + geom_text(aes(label =`Study object`), size=4, position=position_dodge(0.9), angle=90,vjust=0.5, hjust=-0.04 ) + labs(y="Number of articles", x="Study locations")  + theme_classic()+ ylim(c(0,66))+theme(legend.position = "none")+ scale_fill_brewer(palette = "Dark2") + theme(text=element_text(size=18,  family="Times"), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

#p1


```




```{r Hydrology, fig.height=9}
DF_Hydro <- DF %>%  group_by(`Area of study`, Process, Methodology, `Study object`) %>% summarise(n = n()) %>% ungroup() %>%
  dplyr::filter(`Area of study`== "Hydrology")
#%>% mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% dplyr::filter(!is.na(`Area of study`))

Hydro1 <- ggplot(DF_Hydro) + geom_col(aes(x = Process, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Hydro2 <- ggplot(DF_Hydro) + geom_col(aes(x = Methodology, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Hydro3 <- ggplot(DF_Hydro) + geom_col(aes(x = `Study object`, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) 
(Hydro1 + Hydro2)/Hydro3
```

```{r Ecosys, fig.height=9}
DF_Ecosys <- DF %>%  group_by(`Area of study`, Process, Methodology, `Study object`) %>% summarise(n = n()) %>% ungroup() %>%
  dplyr::filter(`Area of study`== "Ecosystem functioning and services")
#%>% mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% dplyr::filter(!is.na(`Area of study`))

Ecosys1 <- ggplot(DF_Ecosys) + geom_col(aes(x = Process, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Ecosys2 <- ggplot(DF_Ecosys) + geom_col(aes(x = Methodology, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Ecosys3 <- ggplot(DF_Ecosys) + geom_col(aes(x = `Study object`, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) 
#(Ecosys1 + Ecosys2)/Ecosys3
```

```{r Social, fig.height=9, fig.width=7}
DF_Social <- DF %>%  group_by(`Area of study`, Process, Methodology, `Study object`) %>% summarise(n = n()) %>% ungroup() %>%
  dplyr::filter(`Area of study`== "Social-ecological")
#%>% mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% dplyr::filter(!is.na(`Area of study`))

Social1 <- ggplot(DF_Social) + geom_col(aes(x = Process, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Social2 <- ggplot(DF_Social) + geom_col(aes(x = Methodology, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Social3 <- ggplot(DF_Social) + geom_col(aes(x = `Study object`, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) 
(Social1 + Social2)/Social3
```

```{r Fresh, fig.height=9}
DF_Fresh <- DF %>%  group_by(`Area of study`, Process, Methodology, `Study object`) %>% summarise(n = n()) %>% ungroup() %>%
  dplyr::filter(`Area of study`== "Freshwater biodiversity")
#%>% mutate(`Area of study`= str_wrap(`Area of study`, 24)) %>% dplyr::filter(!is.na(`Area of study`))

Fresh1 <- ggplot(DF_Fresh) + geom_col(aes(x = Process, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Fresh2 <- ggplot(DF_Fresh) + geom_col(aes(x = Methodology, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
Fresh3 <- ggplot(DF_Fresh) + geom_col(aes(x = `Study object`, y=n)) +labs(y="Number of articles", x=" ")  + theme_classic()+   theme(text=element_text(size=18,  family="Times"))+ theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) 
(Fresh1 + Fresh2)/Fresh3
```

